locale: "en-US"
title: "Zixuan Chen's Homepage"
title_separator: "-"
name: "Zixuan Chen"
description: "Zixuan Chen - Homepage"

url: "https://zixuan-chen.github.io"
baseurl: ""
repository: "zixuan-chen/zixuan-chen.github.io"

author_profile: true

author:
  avatar: "profile.png"
  name: "Zixuan Chen"
  bio: "Ph.D. Candidate @ SJTU"
  location: "Shanghai, China"
  employer: "Shanghai Jiao Tong University"
  email: "m13953842591@sjtu.edu.cn"
  googlescholar: "https://scholar.google.com/citations?user=cMiTyacAAAAJ"
  github: "zixuan-chen"

include:
  - .htaccess
  - _pages
  - files

exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .github
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - CHANGELOG
  - Capfile
  - config
  - Dockerfile
  - Gemfile.lock
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - local
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - vendor

keep_files:
  - .git
  - .svn

encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

sass:
  sass_dir: _sass
  style: compressed

permalink: /:categories/:title/
timezone: Etc/UTC

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

whitelist:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

compress_html:
  clippings: all
  ignore:
    envs: development